### ISSUE TITLE
NPE when started without --onupdate

### ISSUE THREAD

**Issue by solsson** [Yolean/kafka-keyvalue#2]
Startup fails when there's no onupdate URL.

**Comment by solsson** [comment]
```
cache1_1                 | java.lang.NullPointerException
cache1_1                 | 	at se.yolean.kafka.keyvalue.KeyvalueUpdateProcessor.process(KeyvalueUpdateProcessor.java:128)
cache1_1                 | 	at se.yolean.kafka.keyvalue.KeyvalueUpdateProcessor.process(KeyvalueUpdateProcessor.java:122)
cache1_1                 | 	at se.yolean.kafka.keyvalue.KeyvalueUpdateProcessor.process(KeyvalueUpdateProcessor.java:22)
cache1_1                 | 	at org.apache.kafka.streams.processor.internals.ProcessorNode.process(ProcessorNode.java:115)
cache1_1                 | 	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:146)
cache1_1                 | 	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:129)
cache1_1                 | 	at org.apache.kafka.streams.processor.internals.ProcessorContextImpl.forward(ProcessorContextImpl.java:93)
cache1_1                 | 	at org.apache.kafka.streams.processor.internals.SourceNode.process(SourceNode.java:84)
cache1_1                 | 	at org.apache.kafka.streams.processor.internals.StreamTask.process(StreamTask.java:351)
cache1_1                 | 	at org.apache.kafka.streams.processor.internals.AssignedStreamsTasks.process(AssignedStreamsTasks.java:104)
cache1_1                 | 	at org.apache.kafka.streams.processor.internals.TaskManager.process(TaskManager.java:413)
cache1_1                 | 	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:862)
cache1_1                 | 	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:777)
cache1_1                 | 	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:747)
```
