### ISSUE TITLE
Readiness fails when low water mark == high water mark

### ISSUE THREAD

**Issue by solsson** [Yolean/kafka-keyvalue#44]
## Observed behavior

When logs include `Got assigned offset X for testtopic-0; seeking to low water mark X` and X > 0 the KKV container reports readiness down and responds 503 with empty body on /cache/v1 endpoints.

This occurs when retention < age of last message. Note that new empty topics work.

```
2022-02-19 19:49:36,177 DEBUG [org.apa.kaf.cli.Metadata] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-topic, groupId=testgroup] Not replacing existing epoch 380 with new epoch 380 for partition testtopic-0
2022-02-19 19:49:36,177 INFO  [se.yol.kaf.key.ConsumerAtLeastOnce] (smallrye-kafka-consumer-thread-0) Got assigned offset 23230 for testtopic-0; seeking to low water mark 23230
2022-02-19 19:49:36,177 INFO  [io.sma.rea.mes.kafka] (smallrye-kafka-consumer-thread-0) SRMSG18225: Executed consumer assigned re-balance listener for group 'testgroup'
...
2022-02-19 19:50:50,848 INFO  [io.sma.health] (executor-thread-1) SRHCK01001: Reporting health down status: {"status":"DOWN","checks":[{"name":"SmallRye Reactive Messaging - readiness check","status":"UP"},{"name":"consume-loop","status":"DOWN","data":{"stage":"Resetting"}}]}
2022-02-19 19:51:00,858 INFO  [io.sma.health] (executor-thread-1) SRHCK01001: Reporting health down status: {"status":"DOWN","checks":[{"name":"SmallRye Reactive Messaging - readiness check","status":"UP"},{"name":"consume-loop","status":"DOWN","data":{"stage":"Resetting"}}]}
2022-02-19 19:51:09,358 ERROR [org.jbo.res.res.i18n] (executor-thread-1) RESTEASY002010: Failed to execute: javax.ws.rs.ServiceUnavailableException: Denied because cache is unready, check /health for status
	at se.yolean.kafka.keyvalue.http.CacheResource.requireUpToDateCache(CacheResource.java:60)
	at se.yolean.kafka.keyvalue.http.CacheResource.valueByKey(CacheResource.java:93)
	at se.yolean.kafka.keyvalue.http.CacheResource_Subclass.valueByKey$$superforward1(CacheResource_Subclass.zig:229)
	at se.yolean.kafka.keyvalue.http.CacheResource_Subclass$$function$$1.apply(CacheResource_Subclass$$function$$1.zig:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.resteasy.runtime.QuarkusRestPathTemplateInterceptor.restMethodInvoke(QuarkusRestPathTemplateInterceptor.java:31)
	at io.quarkus.resteasy.runtime.QuarkusRestPathTemplateInterceptor_Bean.intercept(QuarkusRestPathTemplateInterceptor_Bean.zig:328)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at se.yolean.kafka.keyvalue.http.CacheResource_Subclass.valueByKey(CacheResource_Subclass.zig:358)
```

```
$ curl -I $KKV/cache/v1/keys
HTTP/1.1 503 Service Unavailable
connection: keep-alive
```

## Expected behavior

Readiness, provided `SmallRye Reactive Messaging - readiness check` is `UP` (which is inherent in how Quarkus health checks work).

Not ready if consumer "stage" goes from `Polling` to  `Resetting` because in such case the cache was operational but may now be out of date.

Not ready if "stage" hasn't reached `Resetting` yet.

**Comment by solsson** [comment]
I suspect that the current qickfix from https://github.com/Yolean/kafka-keyvalue/pull/43 does not reset the rule upon resumed consumption. Logs keep adding:

```
2022-02-20 09:16:56,615 INFO  [se.yol.kaf.key.ConsumerAtLeastOnce] (executor-thread-0) Reporting readiness OK at phase Resetting, presumably low==high watermark
2022-02-20 09:17:06,617 INFO  [se.yol.kaf.key.ConsumerAtLeastOnce] (executor-thread-0) Reporting readiness OK at phase Resetting, presumably low==high watermark
```
