### ISSUE TITLE
NPE for REST requests at shutdown

### ISSUE THREAD

**Issue by solsson** [Yolean/kafka-keyvalue#7]
```
cache1_1                 | [qtp169833205-30] WARN org.eclipse.jetty.server.HttpChannel - /cache/v1/raw/test1
cache1_1                 | javax.servlet.ServletException: java.lang.NullPointerException
cache1_1                 | 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:408)
cache1_1                 | 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
cache1_1                 | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)
cache1_1                 | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)
cache1_1                 | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
cache1_1                 | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:867)
cache1_1                 | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
cache1_1                 | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
cache1_1                 | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
cache1_1                 | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
cache1_1                 | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
cache1_1                 | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
cache1_1                 | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
cache1_1                 | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
cache1_1                 | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
cache1_1                 | 	at org.eclipse.jetty.server.Server.handle(Server.java:502)
cache1_1                 | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364)
cache1_1                 | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
cache1_1                 | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
cache1_1                 | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
cache1_1                 | 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
cache1_1                 | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
cache1_1                 | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
cache1_1                 | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
cache1_1                 | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
cache1_1                 | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
cache1_1                 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
cache1_1                 | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
cache1_1                 | 	at java.base/java.lang.Thread.run(Thread.java:834)
cache1_1                 | Caused by: java.lang.NullPointerException
cache1_1                 | 	at se.yolean.kafka.keyvalue.KeyvalueUpdateProcessor.getValue(KeyvalueUpdateProcessor.java:139)
cache1_1                 | 	at se.yolean.kafka.keyvalue.Endpoints.getCacheValue(Endpoints.java:50)
cache1_1                 | 	at se.yolean.kafka.keyvalue.Endpoints.valueByKey(Endpoints.java:61)
cache1_1                 | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
cache1_1                 | 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
cache1_1                 | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
cache1_1                 | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
cache1_1                 | 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
cache1_1                 | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
cache1_1                 | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
cache1_1                 | 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
cache1_1                 | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
cache1_1                 | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
cache1_1                 | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
cache1_1                 | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
cache1_1                 | 	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
cache1_1                 | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
cache1_1                 | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
cache1_1                 | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
cache1_1                 | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
cache1_1                 | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
cache1_1                 | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
cache1_1                 | 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
cache1_1                 | 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:679)
cache1_1                 | 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
cache1_1                 | 	... 28 more
```

**Comment by solsson** [comment]
This looks solved after Main does the enabling of the http service, upon readiness checks
